# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorNearData/SensorStates.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!SensorNearData/SensorStates.proto\x12\x02pb*U\n\x0cSensorStates\x12\x0f\n\x0bSTATE_FAULT\x10\x00\x12\x0c\n\x08STATE_OK\x10\x01\x12\x11\n\rSTATE_TIMEOUT\x10\x02\x12\x13\n\x0fSTATE_NOT_EXIST\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SensorNearData.SensorStates_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORSTATES._serialized_start=41
  _SENSORSTATES._serialized_end=126
# @@protoc_insertion_point(module_scope)
