# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorNearData/VehicleDynamics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PB.header_pb2 as header__pb2
import PB.SensorNearData.SensorStates_pb2 as SensorNearData_dot_SensorStates__pb2
#from SensorNearData import SensorStates_pb2 as SensorNearData_dot_SensorStates__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$SensorNearData/VehicleDynamics.proto\x12\x11pb.SensorNearData\x1a\x0cheader.proto\x1a!SensorNearData/SensorStates.proto\"\x98\x05\n\x0fVehicleDynamics\x12\x1a\n\x06header\x18\x01 \x01(\x0b\x32\n.pb.Header\x12\x35\n\x04\x65rrs\x18\x03 \x01(\x0b\x32\'.pb.SensorNearData.VehicleDynamics.Errs\x12;\n\x07signals\x18\x04 \x01(\x0b\x32*.pb.SensorNearData.VehicleDynamics.Signals\x12?\n\tvariances\x18\x05 \x01(\x0b\x32,.pb.SensorNearData.VehicleDynamics.Variances\x12@\n\ntimestamps\x18\x07 \x01(\x0b\x32,.pb.SensorNearData.VehicleDynamics.Timestamp\x1a\x86\x01\n\x04\x45rrs\x12;\n\x14steering_wheel_angle\x18\x07 \x01(\x0e\x32\x10.pb.SensorStates:\x0bSTATE_FAULT\x12\x41\n\x1asteering_wheel_angle_speed\x18\x08 \x01(\x0e\x32\x10.pb.SensorStates:\x0bSTATE_FAULT\x1aK\n\x07Signals\x12\x1c\n\x14steering_wheel_angle\x18\x07 \x01(\x02\x12\"\n\x1asteering_wheel_angle_speed\x18\x08 \x01(\x02\x1aM\n\tVariances\x12\x1c\n\x14steering_wheel_angle\x18\x07 \x01(\x02\x12\"\n\x1asteering_wheel_angle_speed\x18\x08 \x01(\x02\x1aM\n\tTimestamp\x12\x1c\n\x14steering_wheel_angle\x18\x07 \x01(\x12\x12\"\n\x1asteering_wheel_angle_speed\x18\x08 \x01(\x12')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SensorNearData.VehicleDynamics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VEHICLEDYNAMICS._serialized_start=109
  _VEHICLEDYNAMICS._serialized_end=773
  _VEHICLEDYNAMICS_ERRS._serialized_start=404
  _VEHICLEDYNAMICS_ERRS._serialized_end=538
  _VEHICLEDYNAMICS_SIGNALS._serialized_start=540
  _VEHICLEDYNAMICS_SIGNALS._serialized_end=615
  _VEHICLEDYNAMICS_VARIANCES._serialized_start=617
  _VEHICLEDYNAMICS_VARIANCES._serialized_end=694
  _VEHICLEDYNAMICS_TIMESTAMP._serialized_start=696
  _VEHICLEDYNAMICS_TIMESTAMP._serialized_end=773
# @@protoc_insertion_point(module_scope)
