# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HMI/CanButton.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13HMI/CanButton.proto\x12\x06pb.HMI\x1a\x0cheader.proto\"\x9a\x01\n\x0b\x42uttonState\x12\x1a\n\x06header\x18\x01 \x01(\x0b\x32\n.pb.Header\x12\x38\n\x10\x41\x63tStatForButton\x18\x02 \x01(\x0e\x32\x1e.pb.HMI.ButtonState.butstate_t\"5\n\nbutstate_t\x12\x13\n\x0f\x42UTTON_RELEASED\x10\x00\x12\x12\n\x0e\x42UTTON_CLICKED\x10\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HMI.CanButton_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUTTONSTATE._serialized_start=46
  _BUTTONSTATE._serialized_end=200
  _BUTTONSTATE_BUTSTATE_T._serialized_start=147
  _BUTTONSTATE_BUTSTATE_T._serialized_end=200
# @@protoc_insertion_point(module_scope)
