# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HMI/HMICanKeyboard.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


#import header_pb2 as header__pb2
import PB.header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18HMI/HMICanKeyboard.proto\x12\x06pb.HMI\x1a\x0cheader.proto\"\xf8\t\n\x13HmiCanKeyboardState\x12\x1a\n\x06header\x18\x01 \x01(\x0b\x32\n.pb.Header\x12]\n\x15\x43\x61nKeyboard_Button_01\x18\x02 \x01(\x0e\x32\x30.pb.HMI.HmiCanKeyboardState.can_keyboard_state_t:\x0c\x42UTTON_UNDEF\x12]\n\x15\x43\x61nKeyboard_Button_02\x18\x03 \x01(\x0e\x32\x30.pb.HMI.HmiCanKeyboardState.can_keyboard_state_t:\x0c\x42UTTON_UNDEF\x12]\n\x15\x43\x61nKeyboard_Button_03\x18\x04 \x01(\x0e\x32\x30.pb.HMI.HmiCanKeyboardState.can_keyboard_state_t:\x0c\x42UTTON_UNDEF\x12]\n\x15\x43\x61nKeyboard_Button_04\x18\x05 \x01(\x0e\x32\x30.pb.HMI.HmiCanKeyboardState.can_keyboard_state_t:\x0c\x42UTTON_UNDEF\x12]\n\x15\x43\x61nKeyboard_Button_05\x18\x06 \x01(\x0e\x32\x30.pb.HMI.HmiCanKeyboardState.can_keyboard_state_t:\x0c\x42UTTON_UNDEF\x12]\n\x15\x43\x61nKeyboard_Button_06\x18\x07 \x01(\x0e\x32\x30.pb.HMI.HmiCanKeyboardState.can_keyboard_state_t:\x0c\x42UTTON_UNDEF\x12]\n\x15\x43\x61nKeyboard_Button_07\x18\x08 \x01(\x0e\x32\x30.pb.HMI.HmiCanKeyboardState.can_keyboard_state_t:\x0c\x42UTTON_UNDEF\x12]\n\x15\x43\x61nKeyboard_Button_08\x18\t \x01(\x0e\x32\x30.pb.HMI.HmiCanKeyboardState.can_keyboard_state_t:\x0c\x42UTTON_UNDEF\x12]\n\x15\x43\x61nKeyboard_Button_09\x18\n \x01(\x0e\x32\x30.pb.HMI.HmiCanKeyboardState.can_keyboard_state_t:\x0c\x42UTTON_UNDEF\x12]\n\x15\x43\x61nKeyboard_Button_10\x18\x0b \x01(\x0e\x32\x30.pb.HMI.HmiCanKeyboardState.can_keyboard_state_t:\x0c\x42UTTON_UNDEF\x12]\n\x15\x43\x61nKeyboard_Button_11\x18\x0c \x01(\x0e\x32\x30.pb.HMI.HmiCanKeyboardState.can_keyboard_state_t:\x0c\x42UTTON_UNDEF\x12]\n\x15\x43\x61nKeyboard_Button_12\x18\r \x01(\x0e\x32\x30.pb.HMI.HmiCanKeyboardState.can_keyboard_state_t:\x0c\x42UTTON_UNDEF\"Q\n\x14\x63\x61n_keyboard_state_t\x12\x10\n\x0c\x42UTTON_UNDEF\x10\x00\x12\x13\n\x0f\x42UTTON_RELEASED\x10\x01\x12\x12\n\x0e\x42UTTON_CLICKED\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HMI.HMICanKeyboard_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HMICANKEYBOARDSTATE._serialized_start=51
  _HMICANKEYBOARDSTATE._serialized_end=1323
  _HMICANKEYBOARDSTATE_CAN_KEYBOARD_STATE_T._serialized_start=1242
  _HMICANKEYBOARDSTATE_CAN_KEYBOARD_STATE_T._serialized_end=1323
# @@protoc_insertion_point(module_scope)
